"""
Google Calendar integration for OIKOS.
Uses OAuth 2.0 (web flow). Tokens stored per-household in CalendarToken table.
"""

import os
from datetime import datetime, timezone
from dotenv import load_dotenv
from sqlalchemy.orm import Session
from google_auth_oauthlib.flow import Flow
from googleapiclient.discovery import build
from google.auth.transport.requests import Request
import google.oauth2.credentials

load_dotenv()

GOOGLE_CLIENT_ID     = os.getenv("GOOGLE_CLIENT_ID", "")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET", "")
GOOGLE_REDIRECT_URI  = os.getenv("GOOGLE_REDIRECT_URI", "http://localhost:8000/api/calendar/callback")

SCOPES = [
    "https://www.googleapis.com/auth/calendar.events",
    "https://www.googleapis.com/auth/gmail.send",
]

_CLIENT_CONFIG = {
    "web": {
        "client_id":     GOOGLE_CLIENT_ID,
        "client_secret": GOOGLE_CLIENT_SECRET,
        "auth_uri":      "https://accounts.google.com/o/oauth2/auth",
        "token_uri":     "https://oauth2.googleapis.com/token",
        "redirect_uris": [GOOGLE_REDIRECT_URI],
    }
}


# ── OAuth helpers ─────────────────────────────────────────────────────────────

def get_auth_url(household_id: str) -> str:
    """Generate Google OAuth consent URL for the household."""
    flow = Flow.from_client_config(
        _CLIENT_CONFIG, scopes=SCOPES, redirect_uri=GOOGLE_REDIRECT_URI
    )
    auth_url, _ = flow.authorization_url(
        access_type="offline",
        include_granted_scopes="true",
        state=household_id,
        prompt="consent",
    )
    return auth_url


def exchange_code(code: str, household_id: str, db: Session) -> None:
    """Exchange OAuth code for tokens and persist to DB."""
    from models.household import CalendarToken

    flow = Flow.from_client_config(
        _CLIENT_CONFIG, scopes=SCOPES, redirect_uri=GOOGLE_REDIRECT_URI, state=household_id
    )
    flow.fetch_token(code=code)
    creds = flow.credentials

    token = db.query(CalendarToken).filter(CalendarToken.household_id == household_id).first()
    if not token:
        token = CalendarToken(household_id=household_id)
        db.add(token)

    token.access_token  = creds.token
    token.refresh_token = creds.refresh_token
    token.token_expiry  = creds.expiry
    db.commit()


def get_connection_status(household_id: str, db: Session) -> dict:
    from models.household import CalendarToken
    token = db.query(CalendarToken).filter(CalendarToken.household_id == household_id).first()
    return {"connected": token is not None, "household_id": household_id}


def disconnect(household_id: str, db: Session) -> None:
    from models.household import CalendarToken
    token = db.query(CalendarToken).filter(CalendarToken.household_id == household_id).first()
    if token:
        db.delete(token)
        db.commit()


def get_credentials(household_id: str, db: Session):
    """Return refreshed google.oauth2.credentials.Credentials for the household."""
    from models.household import CalendarToken
    token_row = db.query(CalendarToken).filter(CalendarToken.household_id == household_id).first()
    if not token_row:
        raise ValueError("Google account not connected for this household.")

    creds = google.oauth2.credentials.Credentials(
        token=token_row.access_token,
        refresh_token=token_row.refresh_token,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=GOOGLE_CLIENT_ID,
        client_secret=GOOGLE_CLIENT_SECRET,
        scopes=SCOPES,
    )
    if token_row.token_expiry:
        expiry = token_row.token_expiry
        if expiry.tzinfo is None:
            expiry = expiry.replace(tzinfo=timezone.utc)
        if expiry <= datetime.now(timezone.utc):
            creds.refresh(Request())
            token_row.access_token = creds.token
            token_row.token_expiry = creds.expiry
            db.commit()
    return creds


def _get_service(household_id: str, db: Session):
    """Return an authenticated Google Calendar API service."""
    creds = get_credentials(household_id, db)
    return build("calendar", "v3", credentials=creds, cache_discovery=False)


# ── Event creation ────────────────────────────────────────────────────────────

def _trip_description(plan: dict) -> str:
    return (
        f"Planned by OIKOS\n\n"
        f"✈️ FLIGHT\n{plan.get('flight_info', 'TBD')}\n\n"
        f"🏨 HOTEL\n{plan.get('hotel_info', 'TBD')}\n\n"
        f"💰 BUDGET\n"
        f"Estimated total: ${plan.get('estimated_cost', 0):,.2f}\n"
        f"{plan.get('notes', '')}\n\n"
        f"Plan generated by OIKOS household assistant."
    )


def create_trip_event(household_id: str, trip_plan: dict, db: Session) -> dict:
    """Create a multi-day trip event in the household's Google Calendar."""
    try:
        service = _get_service(household_id, db)
    except ValueError as e:
        return {"success": False, "error": str(e)}

    try:
        event = {
            "summary":     f"✈️ {trip_plan['title']}",
            "description": _trip_description(trip_plan),
            "start":       {"date": trip_plan["start_date"]},
            "end":         {"date": trip_plan["end_date"]},
            "colorId":     "3",   # Grape (purple)
        }
        result = service.events().insert(calendarId="primary", body=event).execute()
        return {
            "success":    True,
            "event_id":   result["id"],
            "event_link": result.get("htmlLink", ""),
        }
    except Exception as e:
        print(f"[Calendar] create_trip_event error: {e}")
        return {"success": False, "error": str(e)}


def create_reminder_event(
    household_id: str, title: str, date: str, description: str, db: Session
) -> dict:
    """Create a single all-day reminder event (green/sage)."""
    try:
        service = _get_service(household_id, db)
    except ValueError as e:
        return {"success": False, "error": str(e)}

    try:
        event = {
            "summary":     title,
            "description": description,
            "start":       {"date": date},
            "end":         {"date": date},
            "colorId":     "2",   # Sage (green)
        }
        result = service.events().insert(calendarId="primary", body=event).execute()
        return {"success": True, "event_id": result["id"], "event_link": result.get("htmlLink", "")}
    except Exception as e:
        print(f"[Calendar] create_reminder_event error: {e}")
        return {"success": False, "error": str(e)}


# ── Save confirmed trip to DB ─────────────────────────────────────────────────

def save_planned_trip(
    household_id: str,
    trip_plan: dict,
    calendar_event_id: str,
    db: Session,
) -> None:
    from models.household import PlannedTrip
    import uuid

    trip = PlannedTrip(
        id=str(uuid.uuid4()),
        household_id=household_id,
        title=trip_plan.get("title", ""),
        destination=trip_plan.get("destination", ""),
        start_date=trip_plan.get("start_date", ""),
        end_date=trip_plan.get("end_date", ""),
        total_cost=float(trip_plan.get("estimated_cost", 0)),
        calendar_event_id=calendar_event_id,
        status="confirmed",
    )
    db.add(trip)
    db.commit()
